name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Ruby ${{ matrix.ruby }} / ${{ matrix.gemfile }}
    strategy:
      matrix:
        gemfile: [Gemfile, gemfiles/rails_6_0.gemfile, gemfiles/rails_edge.gemfile]
        ruby: [2.7, 3.0]
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Set up database
      run: RAILS_ENV=test bundle exec rails db:setup
    - name: Ruby Tests
      run: bundle exec rails test
    - name: System Tests
      run: bundle exec rails test:system
    - name: Archive system test artifacts
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: screenshots
        path: test/dummy/tmp/screenshots
  lint:
    runs-on: ubuntu-latest
    name: Rubocop
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: RuboCop
      run: bundle exec rubocop

  docs:
    runs-on: ubuntu-latest
    name: Documentation
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Documentation written correctly
      run: bundle exec yardoc --no-output --no-save --no-stats --fail-on-warning
